### ISSUE TITLE
機能について

### ISSUE THREAD

**Issue by c0a2103528** [c0a2108975/ProjExD#3]
https://github.com/c0a2108975/ProjExD/blob/79e7014617d47cf9061b4e6817c7d5d5a788e526/ex02/calc.py#L64-L73
「+」と「^」のボタンが両方とも足し算になっている。

**Comment by c0a2108975** [comment]
当初の考えで「＾」をべき乗にしようと考えていたのですが、べき乗を「＊＊」に変更した後、「＾」の機能を消さなかったためだと考えられます。ご指摘ありがとうございます。変更しました。
