### ISSUE TITLE
If文

### ISSUE THREAD

**Issue by c0a2103528** [c0a2108975/ProjExD#8]
https://github.com/c0a2108975/ProjExD/blob/ad7a340cf6967d8c68c95264159669c1ec79c343/ex04/dodge_bomb.py#L63-L74
if文が多く感じる。
x,y座標を変更する前のものを保存しておき、
check_bound(---) != (1,1)
の際に保存しておいたデータに戻すとより短い文で書けると思う。

**Comment by c0a2108975** [comment]
意見ありがとうごさいます。私もif文が多く感じたのですが、今回はこれが精一杯でした。今回の問題点は次回以降の参考にしたいと思います。
