### ISSUE TITLE
BGM

### ISSUE THREAD

**Issue by c0a2103528** [c0a2108975/ProjExD#9]
https://github.com/c0a2108975/ProjExD/blob/3b4958722520589a988ea4d28c1cbe6a82a25c75/ex05/fight_kokaton.py#L6-L9
私自身、BGMを実装していなかったので良いと感じました。また、選曲も最高でした！
コードの書き方を参考にさせていただいてもよろしいですか？

**Comment by c0a2108975** [comment]
ありがとうございます。ぜひ参考にしてみてください！
